---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rhel8
    image: registry.redhat.io/ubi8/ubi:latest 
    registry:
      url: registry.redhat.io
      credentials:
        username: $REDHAT_USER
        password: $REDHAT_PASS
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
  - name: rhel7
    image: registry.redhat.io/ubi7/ubi:latest
    registry:
      url: registry.redhat.io
      credentials:
        username: $REDHAT_USER
        password: $REDHAT_PASS
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
#Molecule 2-style verification
#verifier:
  #name: testinfra
  #lint:
  #  name: flake8
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
